### ISSUE TITLE
row, should be col in qsv py command

### ISSUE THREAD

**Issue by Anangaya** [jqnatividad/qsv#791]
**Describe the bug**

row, should be col in qsv py command

**To Reproduce**

```
$ qsv py map d "int(row[0]) + int(row[1])" s.csv
a,b,c,c4,d
1,1,1,a4,2
2,2,2,b4,4
3,3,3,c4,6
```

```
$ qsv py map d "int(col[0]) + int(col[1])" s.csv
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'col' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'col' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'col' is not defined
a,b,c,c4,d
1,1,1,a4,<ERROR>
2,2,2,b4,<ERROR>
3,3,3,c4,<ERROR>
Python errors encountered: 3
```

**Expected behavior**

```
$ qsv py map d "int(col[0]) + int(col[1])" s.csv
a,b,c,c4,d
1,1,1,a4,2
2,2,2,b4,4
3,3,3,c4,6`
```

**Comment by jqnatividad** [comment]
Good catch @Anangaya !  Fixed in #793.
