### ISSUE TITLE
BUG: SIGSEGV on processing a CSV file: panicked at 'assertion failed: self.is_char_boundary(new_len)'

### ISSUE THREAD

**Issue by espresso3389** [jqnatividad/qsv#817]
**Describe the bug**
SIGSEGV on processing a CSV file

**To Reproduce**

Do the following command with the attached file

```
qsv stats test.csv  --everything
```

- [test.csv](https://github.com/jqnatividad/qsv/files/10857364/test.csv)

**Expected behavior**

Process the file correctly.

**Screenshots/Backtrace/Sample Data**

```
qsv stats test.csv  --everything
thread '<unnamed>' panicked at 'assertion failed: self.is_char_boundary(new_len)', /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/alloc/src/string.rs:1279:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'assertion failed: self.is_char_boundary(new_len)', thread '<unnamed>' panicked at 'assertion failed: self.is_char_boundary(new_len)', /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/alloc/src/string.rs:1279:13
/rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/alloc/src/string.rs:1279:13
thread '<unnamed>' panicked at 'assertion failed: self.is_char_boundary(new_len)', /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/alloc/src/string.rs:1279:13
thread '<unnamed>' panicked at 'assertion failed: self.is_char_boundary(new_len)', /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/alloc/src/string.rs:1279:13
Segmentation fault (core dumped)
```

**Comment by jqnatividad** [comment]
Thanks for the report @espresso3389 .

However, I can't reproduce this on 0.90.1 running on MacOS/M1.

What version are you using and which platform?  Can you share what `qsv --version` says?
